/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  type AnyPgColumn,
  boolean,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_personnel_role = pgEnum('enum_personnel_role', ['admin', 'chief', 'member'])
export const enum_duty_types_sort_order = pgEnum('enum_duty_types_sort_order', [
  'normal',
  'reverse',
])
export const enum_duty_schedule_status = pgEnum('enum_duty_schedule_status', [
  'draft',
  'scheduled',
  'completed',
])
export const enum_duty_exceptions_status = pgEnum('enum_duty_exceptions_status', [
  'approved',
  'pending',
  'rejected',
])
export const enum_duty_exceptions_types_type = pgEnum('enum_duty_exceptions_types_type', [
  'official',
  'unofficial',
])
export const enum_duty_swap_requests_type = pgEnum('enum_duty_swap_requests_type', [
  'mutual',
  'unilateral',
])
export const enum_duty_swap_requests_status = pgEnum('enum_duty_swap_requests_status', [
  'pending',
  'approved',
  'rejected',
])
export const enum_payload_jobs_log_task_slug = pgEnum('enum_payload_jobs_log_task_slug', [
  'inline',
  'completeDailyDuties',
])
export const enum_payload_jobs_log_state = pgEnum('enum_payload_jobs_log_state', [
  'failed',
  'succeeded',
])
export const enum_payload_jobs_task_slug = pgEnum('enum_payload_jobs_task_slug', [
  'inline',
  'completeDailyDuties',
])

export const personnel_sessions = pgTable(
  'personnel_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('personnel_sessions_order_idx').on(columns._order),
    index('personnel_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [personnel.id],
      name: 'personnel_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const personnel = pgTable(
  'personnel',
  {
    id: serial('id').primaryKey(),
    fullName: varchar('full_name').notNull(),
    rank: numeric('rank', { mode: 'number' }),
    group: integer('group_id').references((): AnyPgColumn => groups.id, {
      onDelete: 'set null',
    }),
    aktif: boolean('aktif').default(true),
    role: enum_personnel_role('role').default('member'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('personnel_group_idx').on(columns.group),
    index('personnel_updated_at_idx').on(columns.updatedAt),
    index('personnel_created_at_idx').on(columns.createdAt),
    uniqueIndex('personnel_email_idx').on(columns.email),
  ],
)

export const groups = pgTable(
  'groups',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    description: varchar('description'),
    chief: integer('chief_id').references((): AnyPgColumn => personnel.id, {
      onDelete: 'set null',
    }),
    cooldownDays: numeric('cooldown_days', { mode: 'number' }).notNull().default(1),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('groups_name_idx').on(columns.name),
    index('groups_chief_idx').on(columns.chief),
    index('groups_updated_at_idx').on(columns.updatedAt),
    index('groups_created_at_idx').on(columns.createdAt),
  ],
)

export const duty_types_year_configs_cron_schedules = pgTable(
  'duty_types_year_configs_cron_schedules',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    cron: varchar('cron').notNull(),
    description: varchar('description').notNull(),
  },
  (columns) => [
    index('duty_types_year_configs_cron_schedules_order_idx').on(columns._order),
    index('duty_types_year_configs_cron_schedules_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [duty_types_year_configs.id],
      name: 'duty_types_year_configs_cron_schedules_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const duty_types_year_configs = pgTable(
  'duty_types_year_configs',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    year: numeric('year', { mode: 'number' }).notNull(),
    isActive: boolean('is_active').default(true),
  },
  (columns) => [
    index('duty_types_year_configs_order_idx').on(columns._order),
    index('duty_types_year_configs_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [duty_types.id],
      name: 'duty_types_year_configs_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const duty_types = pgTable(
  'duty_types',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    group: integer('group_id').references(() => groups.id, {
      onDelete: 'set null',
    }),
    priority: numeric('priority', { mode: 'number' }).notNull().default(10),
    columnOrder: numeric('column_order', { mode: 'number' }).notNull(),
    sortOrder: enum_duty_types_sort_order('sort_order').notNull().default('normal'),
    color: varchar('color').notNull(),
    isActive: boolean('is_active').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('duty_types_group_idx').on(columns.group),
    index('duty_types_updated_at_idx').on(columns.updatedAt),
    index('duty_types_created_at_idx').on(columns.createdAt),
  ],
)

export const duty_schedule = pgTable(
  'duty_schedule',
  {
    id: serial('id').primaryKey(),
    swapRequest: integer('swap_request_id').references((): AnyPgColumn => duty_swap_requests.id, {
      onDelete: 'set null',
    }),
    personnel: integer('personnel_id')
      .notNull()
      .references(() => personnel.id, {
        onDelete: 'set null',
      }),
    dutyType: integer('duty_type_id')
      .notNull()
      .references(() => duty_types.id, {
        onDelete: 'set null',
      }),
    dutyDate: timestamp('duty_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    status: enum_duty_schedule_status('status').notNull().default('scheduled'),
    isOffical: boolean('is_offical'),
    group: integer('group_id')
      .notNull()
      .references(() => groups.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('duty_schedule_swap_request_idx').on(columns.swapRequest),
    index('duty_schedule_personnel_idx').on(columns.personnel),
    index('duty_schedule_duty_type_idx').on(columns.dutyType),
    index('duty_schedule_group_idx').on(columns.group),
    index('duty_schedule_updated_at_idx').on(columns.updatedAt),
    index('duty_schedule_created_at_idx').on(columns.createdAt),
    uniqueIndex('dutyDate_dutyType_group_isOffical_personnel_idx').on(
      columns.dutyDate,
      columns.dutyType,
      columns.group,
      columns.isOffical,
      columns.personnel,
    ),
    index('personnel_dutyDate_idx').on(columns.personnel, columns.dutyDate),
    index('group_dutyDate_idx').on(columns.group, columns.dutyDate),
  ],
)

export const duty_exceptions = pgTable(
  'duty_exceptions',
  {
    id: serial('id').primaryKey(),
    personnel: integer('personnel_id')
      .notNull()
      .references(() => personnel.id, {
        onDelete: 'set null',
      }),
    startDate: timestamp('start_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    reason: varchar('reason').notNull(),
    exceptions_type: integer('exceptions_type_id')
      .notNull()
      .references(() => duty_exceptions_types.id, {
        onDelete: 'set null',
      }),
    status: enum_duty_exceptions_status('status').notNull().default('pending'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('duty_exceptions_personnel_idx').on(columns.personnel),
    index('duty_exceptions_exceptions_type_idx').on(columns.exceptions_type),
    index('duty_exceptions_updated_at_idx').on(columns.updatedAt),
    index('duty_exceptions_created_at_idx').on(columns.createdAt),
    index('personnel_startDate_idx').on(columns.personnel, columns.startDate),
  ],
)

export const duty_exceptions_types = pgTable(
  'duty_exceptions_types',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    type: enum_duty_exceptions_types_type('type').notNull(),
    color: varchar('color').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('duty_exceptions_types_name_idx').on(columns.name),
    index('duty_exceptions_types_updated_at_idx').on(columns.updatedAt),
    index('duty_exceptions_types_created_at_idx').on(columns.createdAt),
  ],
)

export const duty_swap_requests = pgTable(
  'duty_swap_requests',
  {
    id: serial('id').primaryKey(),
    requesterPersonnel: integer('requester_personnel_id')
      .notNull()
      .references(() => personnel.id, {
        onDelete: 'set null',
      }),
    requesterDuty: integer('requester_duty_id')
      .notNull()
      .references((): AnyPgColumn => duty_schedule.id, {
        onDelete: 'set null',
      }),
    type: enum_duty_swap_requests_type('type').notNull(),
    targetPersonnel: integer('target_personnel_id').references(() => personnel.id, {
      onDelete: 'set null',
    }),
    targetDuty: integer('target_duty_id').references((): AnyPgColumn => duty_schedule.id, {
      onDelete: 'set null',
    }),
    status: enum_duty_swap_requests_status('status').notNull().default('pending'),
    approvedBy: integer('approved_by_id').references(() => personnel.id, {
      onDelete: 'set null',
    }),
    approvedAt: timestamp('approved_at', { mode: 'string', withTimezone: true, precision: 3 }),
    notes: varchar('notes'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('duty_swap_requests_requester_personnel_idx').on(columns.requesterPersonnel),
    index('duty_swap_requests_requester_duty_idx').on(columns.requesterDuty),
    index('duty_swap_requests_target_personnel_idx').on(columns.targetPersonnel),
    index('duty_swap_requests_target_duty_idx').on(columns.targetDuty),
    index('duty_swap_requests_approved_by_idx').on(columns.approvedBy),
    index('duty_swap_requests_updated_at_idx').on(columns.updatedAt),
    index('duty_swap_requests_created_at_idx').on(columns.createdAt),
  ],
)

export const personnel_duty_counts = pgTable(
  'personnel_duty_counts',
  {
    id: serial('id').primaryKey(),
    personnel: integer('personnel_id')
      .notNull()
      .references(() => personnel.id, {
        onDelete: 'set null',
      }),
    dutyType: integer('duty_type_id')
      .notNull()
      .references(() => duty_types.id, {
        onDelete: 'set null',
      }),
    count: numeric('count', { mode: 'number' }).default(0),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('personnel_duty_counts_personnel_idx').on(columns.personnel),
    index('personnel_duty_counts_duty_type_idx').on(columns.dutyType),
    index('personnel_duty_counts_updated_at_idx').on(columns.updatedAt),
    index('personnel_duty_counts_created_at_idx').on(columns.createdAt),
    uniqueIndex('personnel_dutyType_idx').on(columns.personnel, columns.dutyType),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_jobs_log = pgTable(
  'payload_jobs_log',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    executedAt: timestamp('executed_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    completedAt: timestamp('completed_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    taskSlug: enum_payload_jobs_log_task_slug('task_slug').notNull(),
    taskID: varchar('task_i_d').notNull(),
    input: jsonb('input'),
    output: jsonb('output'),
    state: enum_payload_jobs_log_state('state').notNull(),
    error: jsonb('error'),
  },
  (columns) => [
    index('payload_jobs_log_order_idx').on(columns._order),
    index('payload_jobs_log_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [payload_jobs.id],
      name: 'payload_jobs_log_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_jobs = pgTable(
  'payload_jobs',
  {
    id: serial('id').primaryKey(),
    input: jsonb('input'),
    completedAt: timestamp('completed_at', { mode: 'string', withTimezone: true, precision: 3 }),
    totalTried: numeric('total_tried', { mode: 'number' }).default(0),
    hasError: boolean('has_error').default(false),
    error: jsonb('error'),
    taskSlug: enum_payload_jobs_task_slug('task_slug'),
    queue: varchar('queue').default('default'),
    waitUntil: timestamp('wait_until', { mode: 'string', withTimezone: true, precision: 3 }),
    processing: boolean('processing').default(false),
    meta: jsonb('meta'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_jobs_completed_at_idx').on(columns.completedAt),
    index('payload_jobs_total_tried_idx').on(columns.totalTried),
    index('payload_jobs_has_error_idx').on(columns.hasError),
    index('payload_jobs_task_slug_idx').on(columns.taskSlug),
    index('payload_jobs_queue_idx').on(columns.queue),
    index('payload_jobs_wait_until_idx').on(columns.waitUntil),
    index('payload_jobs_processing_idx').on(columns.processing),
    index('payload_jobs_updated_at_idx').on(columns.updatedAt),
    index('payload_jobs_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    personnelID: integer('personnel_id'),
    groupsID: integer('groups_id'),
    duty_typesID: integer('duty_types_id'),
    duty_scheduleID: integer('duty_schedule_id'),
    duty_exceptionsID: integer('duty_exceptions_id'),
    duty_exceptions_typesID: integer('duty_exceptions_types_id'),
    duty_swap_requestsID: integer('duty_swap_requests_id'),
    personnel_duty_countsID: integer('personnel_duty_counts_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_personnel_id_idx').on(columns.personnelID),
    index('payload_locked_documents_rels_groups_id_idx').on(columns.groupsID),
    index('payload_locked_documents_rels_duty_types_id_idx').on(columns.duty_typesID),
    index('payload_locked_documents_rels_duty_schedule_id_idx').on(columns.duty_scheduleID),
    index('payload_locked_documents_rels_duty_exceptions_id_idx').on(columns.duty_exceptionsID),
    index('payload_locked_documents_rels_duty_exceptions_types_id_idx').on(
      columns.duty_exceptions_typesID,
    ),
    index('payload_locked_documents_rels_duty_swap_requests_id_idx').on(
      columns.duty_swap_requestsID,
    ),
    index('payload_locked_documents_rels_personnel_duty_counts_id_idx').on(
      columns.personnel_duty_countsID,
    ),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['personnelID']],
      foreignColumns: [personnel.id],
      name: 'payload_locked_documents_rels_personnel_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['groupsID']],
      foreignColumns: [groups.id],
      name: 'payload_locked_documents_rels_groups_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['duty_typesID']],
      foreignColumns: [duty_types.id],
      name: 'payload_locked_documents_rels_duty_types_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['duty_scheduleID']],
      foreignColumns: [duty_schedule.id],
      name: 'payload_locked_documents_rels_duty_schedule_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['duty_exceptionsID']],
      foreignColumns: [duty_exceptions.id],
      name: 'payload_locked_documents_rels_duty_exceptions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['duty_exceptions_typesID']],
      foreignColumns: [duty_exceptions_types.id],
      name: 'payload_locked_documents_rels_duty_exceptions_types_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['duty_swap_requestsID']],
      foreignColumns: [duty_swap_requests.id],
      name: 'payload_locked_documents_rels_duty_swap_requests_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['personnel_duty_countsID']],
      foreignColumns: [personnel_duty_counts.id],
      name: 'payload_locked_documents_rels_personnel_duty_counts_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    personnelID: integer('personnel_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_personnel_id_idx').on(columns.personnelID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['personnelID']],
      foreignColumns: [personnel.id],
      name: 'payload_preferences_rels_personnel_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_jobs_stats = pgTable('payload_jobs_stats', {
  id: serial('id').primaryKey(),
  stats: jsonb('stats'),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const relations_personnel_sessions = relations(personnel_sessions, ({ one }) => ({
  _parentID: one(personnel, {
    fields: [personnel_sessions._parentID],
    references: [personnel.id],
    relationName: 'sessions',
  }),
}))
export const relations_personnel = relations(personnel, ({ one, many }) => ({
  group: one(groups, {
    fields: [personnel.group],
    references: [groups.id],
    relationName: 'group',
  }),
  sessions: many(personnel_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_groups = relations(groups, ({ one }) => ({
  chief: one(personnel, {
    fields: [groups.chief],
    references: [personnel.id],
    relationName: 'chief',
  }),
}))
export const relations_duty_types_year_configs_cron_schedules = relations(
  duty_types_year_configs_cron_schedules,
  ({ one }) => ({
    _parentID: one(duty_types_year_configs, {
      fields: [duty_types_year_configs_cron_schedules._parentID],
      references: [duty_types_year_configs.id],
      relationName: 'cronSchedules',
    }),
  }),
)
export const relations_duty_types_year_configs = relations(
  duty_types_year_configs,
  ({ one, many }) => ({
    _parentID: one(duty_types, {
      fields: [duty_types_year_configs._parentID],
      references: [duty_types.id],
      relationName: 'yearConfigs',
    }),
    cronSchedules: many(duty_types_year_configs_cron_schedules, {
      relationName: 'cronSchedules',
    }),
  }),
)
export const relations_duty_types = relations(duty_types, ({ one, many }) => ({
  group: one(groups, {
    fields: [duty_types.group],
    references: [groups.id],
    relationName: 'group',
  }),
  yearConfigs: many(duty_types_year_configs, {
    relationName: 'yearConfigs',
  }),
}))
export const relations_duty_schedule = relations(duty_schedule, ({ one }) => ({
  swapRequest: one(duty_swap_requests, {
    fields: [duty_schedule.swapRequest],
    references: [duty_swap_requests.id],
    relationName: 'swapRequest',
  }),
  personnel: one(personnel, {
    fields: [duty_schedule.personnel],
    references: [personnel.id],
    relationName: 'personnel',
  }),
  dutyType: one(duty_types, {
    fields: [duty_schedule.dutyType],
    references: [duty_types.id],
    relationName: 'dutyType',
  }),
  group: one(groups, {
    fields: [duty_schedule.group],
    references: [groups.id],
    relationName: 'group',
  }),
}))
export const relations_duty_exceptions = relations(duty_exceptions, ({ one }) => ({
  personnel: one(personnel, {
    fields: [duty_exceptions.personnel],
    references: [personnel.id],
    relationName: 'personnel',
  }),
  exceptions_type: one(duty_exceptions_types, {
    fields: [duty_exceptions.exceptions_type],
    references: [duty_exceptions_types.id],
    relationName: 'exceptions_type',
  }),
}))
export const relations_duty_exceptions_types = relations(duty_exceptions_types, () => ({}))
export const relations_duty_swap_requests = relations(duty_swap_requests, ({ one }) => ({
  requesterPersonnel: one(personnel, {
    fields: [duty_swap_requests.requesterPersonnel],
    references: [personnel.id],
    relationName: 'requesterPersonnel',
  }),
  requesterDuty: one(duty_schedule, {
    fields: [duty_swap_requests.requesterDuty],
    references: [duty_schedule.id],
    relationName: 'requesterDuty',
  }),
  targetPersonnel: one(personnel, {
    fields: [duty_swap_requests.targetPersonnel],
    references: [personnel.id],
    relationName: 'targetPersonnel',
  }),
  targetDuty: one(duty_schedule, {
    fields: [duty_swap_requests.targetDuty],
    references: [duty_schedule.id],
    relationName: 'targetDuty',
  }),
  approvedBy: one(personnel, {
    fields: [duty_swap_requests.approvedBy],
    references: [personnel.id],
    relationName: 'approvedBy',
  }),
}))
export const relations_personnel_duty_counts = relations(personnel_duty_counts, ({ one }) => ({
  personnel: one(personnel, {
    fields: [personnel_duty_counts.personnel],
    references: [personnel.id],
    relationName: 'personnel',
  }),
  dutyType: one(duty_types, {
    fields: [personnel_duty_counts.dutyType],
    references: [duty_types.id],
    relationName: 'dutyType',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_jobs_log = relations(payload_jobs_log, ({ one }) => ({
  _parentID: one(payload_jobs, {
    fields: [payload_jobs_log._parentID],
    references: [payload_jobs.id],
    relationName: 'log',
  }),
}))
export const relations_payload_jobs = relations(payload_jobs, ({ many }) => ({
  log: many(payload_jobs_log, {
    relationName: 'log',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    personnelID: one(personnel, {
      fields: [payload_locked_documents_rels.personnelID],
      references: [personnel.id],
      relationName: 'personnel',
    }),
    groupsID: one(groups, {
      fields: [payload_locked_documents_rels.groupsID],
      references: [groups.id],
      relationName: 'groups',
    }),
    duty_typesID: one(duty_types, {
      fields: [payload_locked_documents_rels.duty_typesID],
      references: [duty_types.id],
      relationName: 'duty_types',
    }),
    duty_scheduleID: one(duty_schedule, {
      fields: [payload_locked_documents_rels.duty_scheduleID],
      references: [duty_schedule.id],
      relationName: 'duty_schedule',
    }),
    duty_exceptionsID: one(duty_exceptions, {
      fields: [payload_locked_documents_rels.duty_exceptionsID],
      references: [duty_exceptions.id],
      relationName: 'duty_exceptions',
    }),
    duty_exceptions_typesID: one(duty_exceptions_types, {
      fields: [payload_locked_documents_rels.duty_exceptions_typesID],
      references: [duty_exceptions_types.id],
      relationName: 'duty_exceptions_types',
    }),
    duty_swap_requestsID: one(duty_swap_requests, {
      fields: [payload_locked_documents_rels.duty_swap_requestsID],
      references: [duty_swap_requests.id],
      relationName: 'duty_swap_requests',
    }),
    personnel_duty_countsID: one(personnel_duty_counts, {
      fields: [payload_locked_documents_rels.personnel_duty_countsID],
      references: [personnel_duty_counts.id],
      relationName: 'personnel_duty_counts',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    personnelID: one(personnel, {
      fields: [payload_preferences_rels.personnelID],
      references: [personnel.id],
      relationName: 'personnel',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_payload_jobs_stats = relations(payload_jobs_stats, () => ({}))

type DatabaseSchema = {
  enum_personnel_role: typeof enum_personnel_role
  enum_duty_types_sort_order: typeof enum_duty_types_sort_order
  enum_duty_schedule_status: typeof enum_duty_schedule_status
  enum_duty_exceptions_status: typeof enum_duty_exceptions_status
  enum_duty_exceptions_types_type: typeof enum_duty_exceptions_types_type
  enum_duty_swap_requests_type: typeof enum_duty_swap_requests_type
  enum_duty_swap_requests_status: typeof enum_duty_swap_requests_status
  enum_payload_jobs_log_task_slug: typeof enum_payload_jobs_log_task_slug
  enum_payload_jobs_log_state: typeof enum_payload_jobs_log_state
  enum_payload_jobs_task_slug: typeof enum_payload_jobs_task_slug
  personnel_sessions: typeof personnel_sessions
  personnel: typeof personnel
  groups: typeof groups
  duty_types_year_configs_cron_schedules: typeof duty_types_year_configs_cron_schedules
  duty_types_year_configs: typeof duty_types_year_configs
  duty_types: typeof duty_types
  duty_schedule: typeof duty_schedule
  duty_exceptions: typeof duty_exceptions
  duty_exceptions_types: typeof duty_exceptions_types
  duty_swap_requests: typeof duty_swap_requests
  personnel_duty_counts: typeof personnel_duty_counts
  payload_kv: typeof payload_kv
  payload_jobs_log: typeof payload_jobs_log
  payload_jobs: typeof payload_jobs
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  payload_jobs_stats: typeof payload_jobs_stats
  relations_personnel_sessions: typeof relations_personnel_sessions
  relations_personnel: typeof relations_personnel
  relations_groups: typeof relations_groups
  relations_duty_types_year_configs_cron_schedules: typeof relations_duty_types_year_configs_cron_schedules
  relations_duty_types_year_configs: typeof relations_duty_types_year_configs
  relations_duty_types: typeof relations_duty_types
  relations_duty_schedule: typeof relations_duty_schedule
  relations_duty_exceptions: typeof relations_duty_exceptions
  relations_duty_exceptions_types: typeof relations_duty_exceptions_types
  relations_duty_swap_requests: typeof relations_duty_swap_requests
  relations_personnel_duty_counts: typeof relations_personnel_duty_counts
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_jobs_log: typeof relations_payload_jobs_log
  relations_payload_jobs: typeof relations_payload_jobs
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_payload_jobs_stats: typeof relations_payload_jobs_stats
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
