/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    personnel: PersonnelAuthOperations;
  };
  blocks: {};
  collections: {
    personnel: Personnel;
    media: Media;
    groups: Group;
    duty_types: DutyType;
    duty_schedule: DutySchedule;
    duty_exceptions: DutyException;
    duty_exceptions_types: DutyExceptionsType;
    duty_swap_requests: DutySwapRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    personnel: PersonnelSelect<false> | PersonnelSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    duty_types: DutyTypesSelect<false> | DutyTypesSelect<true>;
    duty_schedule: DutyScheduleSelect<false> | DutyScheduleSelect<true>;
    duty_exceptions: DutyExceptionsSelect<false> | DutyExceptionsSelect<true>;
    duty_exceptions_types: DutyExceptionsTypesSelect<false> | DutyExceptionsTypesSelect<true>;
    duty_swap_requests: DutySwapRequestsSelect<false> | DutySwapRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Personnel;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface PersonnelAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personnel".
 */
export interface Personnel {
  id: number;
  fullName: string;
  /**
   * Otomatik atanır, 1 = En kıdemli
   */
  rank?: number | null;
  group?: (number | null) | Group;
  role?: ('admin' | 'chief' | 'member') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'personnel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Bu grubun nöbet kıdemlisi (sadece admin atayabilir)
   */
  chief?: (number | null) | Personnel;
  /**
   * Nöbet sonrası izinli gün sayısı (grup bazlı)
   */
  cooldownDays: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_types".
 */
export interface DutyType {
  id: number;
  name: string;
  /**
   * Her yıl için ayrı cron tanımları
   */
  yearConfigs: {
    year:
      | '2026'
      | '2027'
      | '2028'
      | '2029'
      | '2030'
      | '2031'
      | '2032'
      | '2033'
      | '2034'
      | '2035'
      | '2036'
      | '2037'
      | '2038'
      | '2039'
      | '2040';
    cronSchedules: {
      cron: string;
      description: string;
      id?: string | null;
    }[];
    isActive?: boolean | null;
    id?: string | null;
  }[];
  /**
   * Çakışma durumunda düşük sayı yüksek öncelik (1 = en yüksek)
   */
  priority: number;
  columnOrder: number;
  sortOrder: 'normal' | 'reverse';
  /**
   * Bi renk seç
   */
  color: string;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_schedule".
 */
export interface DutySchedule {
  id: number;
  swapRequest?: (number | null) | DutySwapRequest;
  swapHistory?:
    | {
        date: string;
        fromPersonnel: number | Personnel;
        toPersonnel: number | Personnel;
        type: 'mutual' | 'unilateral';
        id?: string | null;
      }[]
    | null;
  personnel: number | Personnel;
  dutyType: number | DutyType;
  dutyDate: string;
  status: 'scheduled' | 'completed' | 'cancelled' | 'swapped' | 'exception';
  exceptionType?: ('official' | 'unofficial') | null;
  /**
   * Sarı mazeret sonrası bir sonraki ay öncelikli
   */
  isPriority?: boolean | null;
  /**
   * Değişim varsa asıl nöbetçi
   */
  originalPersonnel?: (number | null) | Personnel;
  notes?: string | null;
  group: number | Group;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_swap_requests".
 */
export interface DutySwapRequest {
  id: number;
  requesterPersonnel: number | Personnel;
  requesterDuty: number | DutySchedule;
  type: 'mutual' | 'unilateral';
  targetPersonnel?: (number | null) | Personnel;
  targetDuty?: (number | null) | DutySchedule;
  /**
   * Karşılıksız değişimde asıl nöbetçinin mazeret tipi
   */
  excuseType?: ('official' | 'unofficial') | null;
  status: 'pending' | 'approved' | 'rejected';
  approvedBy?: (number | null) | Personnel;
  approvedAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_exceptions".
 */
export interface DutyException {
  id: number;
  personnel: number | Personnel;
  startDate: string;
  endDate: string;
  reason: string;
  exceptions_type: number | DutyExceptionsType;
  status: 'approved' | 'pending' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_exceptions_types".
 */
export interface DutyExceptionsType {
  id: number;
  name: string;
  type: 'official' | 'unofficial';
  /**
   * Bi renk seç
   */
  color: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'personnel';
        value: number | Personnel;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null)
    | ({
        relationTo: 'duty_types';
        value: number | DutyType;
      } | null)
    | ({
        relationTo: 'duty_schedule';
        value: number | DutySchedule;
      } | null)
    | ({
        relationTo: 'duty_exceptions';
        value: number | DutyException;
      } | null)
    | ({
        relationTo: 'duty_exceptions_types';
        value: number | DutyExceptionsType;
      } | null)
    | ({
        relationTo: 'duty_swap_requests';
        value: number | DutySwapRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'personnel';
    value: number | Personnel;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'personnel';
    value: number | Personnel;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personnel_select".
 */
export interface PersonnelSelect<T extends boolean = true> {
  fullName?: T;
  rank?: T;
  group?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  chief?: T;
  cooldownDays?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_types_select".
 */
export interface DutyTypesSelect<T extends boolean = true> {
  name?: T;
  yearConfigs?:
    | T
    | {
        year?: T;
        cronSchedules?:
          | T
          | {
              cron?: T;
              description?: T;
              id?: T;
            };
        isActive?: T;
        id?: T;
      };
  priority?: T;
  columnOrder?: T;
  sortOrder?: T;
  color?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_schedule_select".
 */
export interface DutyScheduleSelect<T extends boolean = true> {
  swapRequest?: T;
  swapHistory?:
    | T
    | {
        date?: T;
        fromPersonnel?: T;
        toPersonnel?: T;
        type?: T;
        id?: T;
      };
  personnel?: T;
  dutyType?: T;
  dutyDate?: T;
  status?: T;
  exceptionType?: T;
  isPriority?: T;
  originalPersonnel?: T;
  notes?: T;
  group?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_exceptions_select".
 */
export interface DutyExceptionsSelect<T extends boolean = true> {
  personnel?: T;
  startDate?: T;
  endDate?: T;
  reason?: T;
  exceptions_type?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_exceptions_types_select".
 */
export interface DutyExceptionsTypesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_swap_requests_select".
 */
export interface DutySwapRequestsSelect<T extends boolean = true> {
  requesterPersonnel?: T;
  requesterDuty?: T;
  type?: T;
  targetPersonnel?: T;
  targetDuty?: T;
  excuseType?: T;
  status?: T;
  approvedBy?: T;
  approvedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}