/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    personnel: PersonnelAuthOperations;
  };
  blocks: {};
  collections: {
    personnel: Personnel;
    groups: Group;
    duty_types: DutyType;
    duty_schedule: DutySchedule;
    duty_exceptions: DutyException;
    duty_exceptions_types: DutyExceptionsType;
    duty_swap_requests: DutySwapRequest;
    personnel_duty_counts: PersonnelDutyCount;
    parent_group: ParentGroup;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    personnel: {
      counts: 'personnel_duty_counts';
      exceptions: 'duty_exceptions';
      schedule: 'duty_schedule';
    };
  };
  collectionsSelect: {
    personnel: PersonnelSelect<false> | PersonnelSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    duty_types: DutyTypesSelect<false> | DutyTypesSelect<true>;
    duty_schedule: DutyScheduleSelect<false> | DutyScheduleSelect<true>;
    duty_exceptions: DutyExceptionsSelect<false> | DutyExceptionsSelect<true>;
    duty_exceptions_types: DutyExceptionsTypesSelect<false> | DutyExceptionsTypesSelect<true>;
    duty_swap_requests: DutySwapRequestsSelect<false> | DutySwapRequestsSelect<true>;
    personnel_duty_counts: PersonnelDutyCountsSelect<false> | PersonnelDutyCountsSelect<true>;
    parent_group: ParentGroupSelect<false> | ParentGroupSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Personnel;
  jobs: {
    tasks: {
      completeDailyDuties: TaskCompleteDailyDuties;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface PersonnelAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personnel".
 */
export interface Personnel {
  id: number;
  fullName: string;
  /**
   * Otomatik atanır, 1 = En kıdemli
   */
  rank?: number | null;
  group?: (number | null) | Group;
  aktif?: boolean | null;
  /**
   * Bu personeli nöbet saysıları.
   */
  counts?: {
    docs?: (number | PersonnelDutyCount)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Bu personeli ait mazeretler.
   */
  exceptions?: {
    docs?: (number | DutyException)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Bu personeli nöbet saysıları.
   */
  schedule?: {
    docs?: (number | DutySchedule)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  role?: ('admin' | 'chief' | 'member') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'personnel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Bu grubun nöbet kıdemlisi (sadece admin atayabilir)
   */
  chief?: (number | null) | Personnel;
  parent_group?: (number | null) | ParentGroup;
  /**
   * Nöbet sonrası izinli gün sayısı (grup bazlı)
   */
  cooldownDays: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parent_group".
 */
export interface ParentGroup {
  id: number;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personnel_duty_counts".
 */
export interface PersonnelDutyCount {
  id: number;
  personnel: number | Personnel;
  dutyType: number | DutyType;
  count?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_types".
 */
export interface DutyType {
  id: number;
  name: string;
  group?: (number | null) | Group;
  year: number;
  cronSchedules: {
    cron: string;
    description: string;
    id?: string | null;
  }[];
  /**
   * Çakışma durumunda düşük sayı yüksek öncelik (1 = en yüksek)
   */
  priority: number;
  sortOrder: 'normal' | 'reverse';
  /**
   * Bi renk seç
   */
  color: string;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_exceptions".
 */
export interface DutyException {
  id: number;
  personnel: number | Personnel;
  startDate: string;
  endDate: string;
  reason: string;
  exceptions_type: number | DutyExceptionsType;
  status: 'approved' | 'pending' | 'rejected';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_exceptions_types".
 */
export interface DutyExceptionsType {
  id: number;
  name: string;
  type: 'official' | 'unofficial';
  /**
   * Bi renk seç
   */
  color: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_schedule".
 */
export interface DutySchedule {
  id: number;
  swapRequest?: (number | null) | DutySwapRequest;
  personnel: number | Personnel;
  dutyType: number | DutyType;
  dutyDate: string;
  status: 'draft' | 'scheduled' | 'completed';
  isOffical?: boolean | null;
  group: number | Group;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_swap_requests".
 */
export interface DutySwapRequest {
  id: number;
  requesterPersonnel: number | Personnel;
  requesterDuty: number | DutySchedule;
  type: 'mutual' | 'unilateral';
  targetPersonnel?: (number | null) | Personnel;
  targetDuty?: (number | null) | DutySchedule;
  status: 'pending' | 'approved' | 'rejected';
  approvedBy?: (number | null) | Personnel;
  approvedAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'completeDailyDuties';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'completeDailyDuties') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'personnel';
        value: number | Personnel;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null)
    | ({
        relationTo: 'duty_types';
        value: number | DutyType;
      } | null)
    | ({
        relationTo: 'duty_schedule';
        value: number | DutySchedule;
      } | null)
    | ({
        relationTo: 'duty_exceptions';
        value: number | DutyException;
      } | null)
    | ({
        relationTo: 'duty_exceptions_types';
        value: number | DutyExceptionsType;
      } | null)
    | ({
        relationTo: 'duty_swap_requests';
        value: number | DutySwapRequest;
      } | null)
    | ({
        relationTo: 'personnel_duty_counts';
        value: number | PersonnelDutyCount;
      } | null)
    | ({
        relationTo: 'parent_group';
        value: number | ParentGroup;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'personnel';
    value: number | Personnel;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'personnel';
    value: number | Personnel;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personnel_select".
 */
export interface PersonnelSelect<T extends boolean = true> {
  fullName?: T;
  rank?: T;
  group?: T;
  aktif?: T;
  counts?: T;
  exceptions?: T;
  schedule?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  chief?: T;
  parent_group?: T;
  cooldownDays?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_types_select".
 */
export interface DutyTypesSelect<T extends boolean = true> {
  name?: T;
  group?: T;
  year?: T;
  cronSchedules?:
    | T
    | {
        cron?: T;
        description?: T;
        id?: T;
      };
  priority?: T;
  sortOrder?: T;
  color?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_schedule_select".
 */
export interface DutyScheduleSelect<T extends boolean = true> {
  swapRequest?: T;
  personnel?: T;
  dutyType?: T;
  dutyDate?: T;
  status?: T;
  isOffical?: T;
  group?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_exceptions_select".
 */
export interface DutyExceptionsSelect<T extends boolean = true> {
  personnel?: T;
  startDate?: T;
  endDate?: T;
  reason?: T;
  exceptions_type?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_exceptions_types_select".
 */
export interface DutyExceptionsTypesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "duty_swap_requests_select".
 */
export interface DutySwapRequestsSelect<T extends boolean = true> {
  requesterPersonnel?: T;
  requesterDuty?: T;
  type?: T;
  targetPersonnel?: T;
  targetDuty?: T;
  status?: T;
  approvedBy?: T;
  approvedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personnel_duty_counts_select".
 */
export interface PersonnelDutyCountsSelect<T extends boolean = true> {
  personnel?: T;
  dutyType?: T;
  count?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parent_group_select".
 */
export interface ParentGroupSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCompleteDailyDuties".
 */
export interface TaskCompleteDailyDuties {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}